name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Validate File
        run: |
         if [ -f wrong.html ]; then
            echo "File exists ✅"
          else
            echo "File missing ❌"
            exit 1
          fi

      - name: Build Step
        run: echo "Build successful 🚀"

